osx_image: xcode8.3
language: objective-c
cache:
  directories:
  - Carthage
before_script:
  - carthage version
  - carthage bootstrap --cache-builds --platform iOS
xcode_project: AppliveryDemo.xcodeproj
xcode_scheme: AppliveryDemo