language: objective-c
osx_image: xcode8
script:
  - xcodebuild -version
  - xcodebuild -project AppliveryDemo.xcodeproj -scheme AppliveryDemo -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6" build